[build]
  publish = "public"
  command = "gatsby build"
[build.environment]
  YARN_VERSION = "1.3.2"
  YARN_FLAGS = "--no-ignore-optional"
[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/xml"